// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH9NdIqfhXBi1f8roJm8NiHAAOFddti88',
    appId: '1:949063013055:web:5946cd4fb928508afaac0a',
    messagingSenderId: '949063013055',
    projectId: 'smart-barrier-dbfea',
    authDomain: 'smart-barrier-dbfea.firebaseapp.com',
    storageBucket: 'smart-barrier-dbfea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAztS2bynLLOzpDOmYdn13B9O7gr-5j-8',
    appId: '1:949063013055:android:7952259f628b9973faac0a',
    messagingSenderId: '949063013055',
    projectId: 'smart-barrier-dbfea',
    storageBucket: 'smart-barrier-dbfea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG63JLAILp0H4gVO2LeKsWdcsIds2iMxc',
    appId: '1:949063013055:ios:3fae4de311bb7a53faac0a',
    messagingSenderId: '949063013055',
    projectId: 'smart-barrier-dbfea',
    storageBucket: 'smart-barrier-dbfea.appspot.com',
    iosClientId: '949063013055-sue0k067m18eq4hm9d25n96hegv3ktkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG63JLAILp0H4gVO2LeKsWdcsIds2iMxc',
    appId: '1:949063013055:ios:3fae4de311bb7a53faac0a',
    messagingSenderId: '949063013055',
    projectId: 'smart-barrier-dbfea',
    storageBucket: 'smart-barrier-dbfea.appspot.com',
    iosClientId: '949063013055-sue0k067m18eq4hm9d25n96hegv3ktkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartParking',
  );
}
